# Generated by Django 4.1.7 on 2023-02-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0005_remove_ads_author_ads_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
