# Generated by Django 4.1.7 on 2023-02-18 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_alter_ads_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username']},
        ),
    ]
